title: Phenotypic reaction of common bean against scab (Elsinoe phaseoli)
description: A dataset describing the reactions of a set on common bean cultivars against the (Elsinoe phaseoli) pathogen that causes scab disease through its virulence factor. The dataset consist of 174 andean diversity panel and 5 local accession which where evaluated under natural infestation of scab in the field in western Kenya.

publisher_text: 
publisher_url: 

license_text: 
license_url: 

frequency: 

certificate_embed: 
